apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "pandemie"
  namespace: "default"
  labels:
    app: "pandemie"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "pandemie"
  template:
    metadata:
      labels:
        app: "pandemie"
    spec:
      containers:
      - name: "pandemie"
        image: "pandemie"
        ports:
          - name: http
            containerPort: 5000
