---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "pandemie"
  namespace: "default"
  labels:
    app: "pandemie"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "pandemie"
  template:
    metadata:
      labels:
        app: "pandemie"
    spec:
      containers:
      - name: "pandemie"
        image: "gcr.io/icpandemie/pandemie"
        ports:
          - name: http
            containerPort: 5000
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "pandemie-hpa"
  namespace: "default"
  labels:
    app: "pandemie"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "pandemie"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80